config/routes.rb
Rails.application.routes.draw do
  resources :items
  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  # def show
  #   @item = Item.find(params[:id])
  # end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])

  end

  def create
    @item = Item.new(item_params)

    if @item.save
      @items = Item.all
      redirect_to items_path
    else
      render 'new'
    end

  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      @items = Item.all
      redirect_to items_path
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to items_path
  end

private

  def item_params
    params.require(:item).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Add a item</h1>
<%= form_for :item, url: item_path(@item), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/items/index.html.erb
<h1>todos</h1>
<%= link_to 'Add task', new_item_path %>

<% @items.each do |item| %>

  <ul><%= item.title %></ul>
  <ul><%= link_to 'Edit', edit_item_path(item.id) %>
      <%= link_to 'Delete', item_path(item),
                            method: :delete
                            # data: {confirm: 'Are you sure?'}
                            %>
  </ul>
  <% end %>

app/views/items/new.html.erb
<h1>Add a item</h1>
<%= form_for :item, url: items_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoItem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>